### ISSUE TITLE
CS1061 “CaptchaViewModel” does not contain “GuidFieldName” definition for and no “GuidFieldName”extension method accepting a first“CaptchaViewModel” argument of type could be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by jiangyo4** [MainBit/MainBit.Captcha#1]
“MainBit.Captcha\Views\EditorTemplates\Parts\Captcha.cshtml”

  7. "@(Model.ValueFieldName)" name="@(Model.ValueFieldName)" 
8."@(Model.GuidFieldName)" name="@(Model.GuidFieldName)" 
  
1.CS1061 “CaptchaViewModel” does not contain “GuidFieldName” definition for and no “GuidFieldName”extension method accepting a first“CaptchaViewModel” argument of type could be found (are you missing a using directive or an assembly reference?)
2.CS1061 “CaptchaViewModel” does not contain “ValueFieldName” definition for and no “ValueFieldName”extension method accepting a first“CaptchaViewModel” argument of type could be found (are you missing a using directive or an assembly reference?)

I  use  vs2015  and  orchard  1.9.3.
please  help!

**Comment by aipetryakov** [comment]
Hi, @jiangyo4

I fixed that bug today and tested it on orchard 1.10.2.
Please, try it again and let me know if it works.

This is very old module that was intended to use with deprecated Custom Forms Orchard Module.
I recommend you to consider using of Dynamic Forms Orchard Module with Anti-Spam Elements Orchard Module for all forms on your website.

**Comment by jiangyo4** [comment]
Hi, @neTp9c 

I  try the   fixed  version  just now, Everything  is fine to  use  MainBit.Captcha   with  Custom Forms on orchard  1.9.3 .
Thank you  very much !
One more  thing, I  want  to use  your  captcha module  on   orchard  registration/login  screen.
How  to do  it?
Thanks  again!

**Comment by jiangyo4** [comment]
Hi, @neTp9c <https://github.com/netp9c>

I try the fixed version just now, Everything is fine to use MainBit.Captcha
with Custom Forms on orchard 1.9.3 .
Thank you very much !
One more thing, I want to use your captcha module on orchard
registration/login screen.
How to do it?
Thanks again!

2017-07-05 5:02 GMT+08:00 Alex Petryakov <notifications@github.com>:

**Comment by aipetryakov** [comment]
@jiangyo4,
one problem per issue, please.

For using this captcha on registration/login  screen you need some coding:
1. Create new module.
2. Add to it the copy of Orchard.Users.Controllers.AccountController
3. Remove from new controller all method except of LogOn and Register.
4. Register new Routes with orchard LogOn and Register url but higher priority.
5. Copy views for the methods to you module.
6. Try if it works.
7. Add generating captcha method to Get methods (like in MainBit.Captcha.Drivers.CaptchaPartDriver)
8. Add validating captcha to Post methods (like in MainBit.Captcha.Drivers.CaptchaPartDriver)
9. Add rendering captcha in View (like in ~/Modules/MainBit.Captcha/Views/EditorTemplates/Parts/Captcha.cshtml)
10. Try if it works again.
